tips:
  - æ¬¢è¿ä½¿ç”¨ TRSS-Yunzai ICQQ Plugin ! ä½œè€…ï¼šæ—¶é›¨ğŸŒŒæ˜Ÿç©º
  - å‚è€ƒï¼šhttps://github.com/TimeRainStarSky/Yunzai-ICQQ-Plugin
permission: master
markdown:
  mode: false
  button: false
  callback: true
bot: {}
token: []
