tips:
  - æ¬¢è¿ä½¿ç”¨ TRSS-Yunzai QQBot Plugin ! ä½œè€…ï¼šæ—¶é›¨ğŸŒŒæ˜Ÿç©º
  - å‚è€ƒï¼šhttps://github.com/TimeRainStarSky/Yunzai-QQBot-Plugin
permission: master
toQRCode: true
toCallback: true
toBotUpload: true
hideGuildRecall: false
imageLength: 3
markdown:
  template: abcdefghij
bot:
  sandbox: false
  maxRetry: .inf
  timeout: 30000
token: []
