tips:
  - æ¬¢è¿ä½¿ç”¨ TRSS Yunzai Plugin ! ä½œè€…ï¼šæ—¶é›¨ğŸŒŒæ˜Ÿç©º
  - æŒ‰ Ctrl+Q Y ä¿å­˜é€€å‡º
  - å‚è€ƒï¼šhttps://Yunzai.TRSS.me
Voice:
  GenshinVoiceApi: ""
  ChatWaifuApi: ""
RealESRGAN:
  api: ""
  format: jpg
RemBG:
  api: ""
miHoYoLogin:
  help: true
